version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: abadrawy/udacity-c3-deployment
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: abadrawy/udacity-c3-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: abadrawy/udacity-c3-restapi-feed  
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: abadrawy/udacity-c3-frontend
