apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - image: scheele/reverseproxy
    name: reverseproxy
    imagePullPolicy: Always          
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"       
    ports:
    - containerPort: 8080
  restartPolicy: Always
kubectl port-forward service/reverseproxy 8080:8080 && kubectl port-forward service frontend 8100:8100